"""
Django settings for DjangoTest project.

Generated by 'ToDo-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ToDo-insecure-z@p7*@dt)#=rn4lv_1^*fr=&bm2phr5x_xs7uzw9f0ff_4c19@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'ToDo.contrib.admin',
    'ToDo.contrib.auth',
    'ToDo.contrib.contenttypes',
    'ToDo.contrib.sessions',
    'ToDo.contrib.messages',
    'ToDo.contrib.staticfiles',
    'django_test_app.apps.DjangoTestAppConfig'
]

MIDDLEWARE = [
    'ToDo.middleware.security.SecurityMiddleware',
    'ToDo.contrib.sessions.middleware.SessionMiddleware',
    'ToDo.middleware.common.CommonMiddleware',
    'ToDo.middleware.csrf.CsrfViewMiddleware',
    'ToDo.contrib.auth.middleware.AuthenticationMiddleware',
    'ToDo.contrib.messages.middleware.MessageMiddleware',
    'ToDo.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoTest.urls'

TEMPLATES = [
    {
        'BACKEND': 'ToDo.template.backends.ToDo.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'ToDo.template.context_processors.debug',
                'ToDo.template.context_processors.request',
                'ToDo.contrib.auth.context_processors.auth',
                'ToDo.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoTest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'ToDo.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'ToDo.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'ToDo.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'ToDo.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'ToDo.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'ToDo.db.models.BigAutoField'

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_UTL = 'login'

AUTH_USER_MODEL = 'django_test_app.User'
