# Generated by Django 5.0.6 on 2024-07-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_test_app', '0005_task_user_alter_task_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
